name: Publish packages

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  build:
    name: Build bundle and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.node }}
        uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies ${{ matrix.node }}
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}
      - name: Login to npm
        run: npm login --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: |
          npm ci
          npm run build
          npm publish --dry-run
